apiVersion: batch/v1
kind: CronJob

metadata:
  name: inventory-sync

spec:

  schedule: "*/2 * * * *"

  jobTemplate:

    spec:

      template:

        spec:

          containers:

          - name: inventory-sync

            image: bhavika79/starlitsun-inventorysync:v4

            envFrom:

            - configMapRef:
                name: starlitsun-config

            - secretRef:
                name: starlitsun-secret

          restartPolicy: Never