apiVersion: batch/v1
kind: Job

metadata:
  name: bulk-product-import

spec:

  template:

    metadata:
      labels:
        app: bulk-product-import

    spec:

      containers:

      - name: importer

        image: bhavika79/starlitsun-bulkimportworker

        envFrom:

        - configMapRef:
            name: starlitsun-config

        - secretRef:
            name: starlitsun-secret

      restartPolicy: Never

  backoffLimit: 2